#!/bin/bash
cp /home/pi/temp_photos/*.jpg /home/pi/photos/
mogrify -resize 968x648 /home/pi/temp_photos/*.jpg
montage /home/pi/temp_photos/*.jpg -tile 2x2 -geometry +10+10 /home/pi/temp_montage2.jpg
montage /home/pi/temp_montage2.jpg /home/pi/photobooth_label.jpg -tile 2x1 -geometry +5+5 /home/pi/temp_montage3.jpg

suffix=$(date +%H%M%S)
#convert -size 352x288 -composite /home/pi/temp_montage2.jpg /home/pi/photobooth_label.jpg  -geometry 64x64+176+144 -depth 8 /home/pi/photos/ran${suffix}.jpg


cp /home/pi/temp_montage3.jpg /home/pi/photos/PB_${suffix}.jpg
sudo python /home/pi/photobooth/pb/fb.py '/home/pi/temp_montage3.jpg'
rm /home/pi/temp_photos/*.jpg
rm /home/pi/temp*
